[package]
name = "mev-share-rs"
version = "0.1.0"
authors = ["Matthias Seitz <matthias.seitz@outlook.de>"]
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
homepage = "https://github.com/mattsse/mev-share-rs"
repository = "https://github.com/mattsse/mev-share-rs"
description = "MEV-share protocol support in rust"

[dependencies]
## eth
ethers-core = { version = "2.0", default-features = false }

## async
async-sse = "5.1"
reqwest = { version = "0.11", features = ["stream"] }
futures-util = { version = "0.3", features = ["io"] }
http-types = { version = "2.12", default-features = false }

## misc
bytes = "1.4"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
pin-project-lite = "0.2"
serde_json = "1.0"
tokio = { version = "1", features = ["time"] }
tracing = "0.1"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt", "rt-multi-thread"] }
